Small fixes

diff --git a/bin/cms_prep b/bin/cms_prep
--- a/bin/cms_prep
+++ b/bin/cms_prep
@@ -18,14 +18,16 @@ site_path=$1
 if [[ -z ${1##*/} ]]; then site_path=${1%/}; fi
 site=${site_path##*/}
 # Перестраховываемся на случай пустого имени сайта
-if [[ -z $site ]]; then echo "Error!"; exit 1; fi
+if [[ -z $site ]]; then echo "Error! Site name is empty"; exit 1; fi
+if [[ -z $new_host ]]; then echo "Error! Destination is empty"; exit 2; fi
 
 if [ -d $move_dir ]; then mkdir -p $move_dir; fi
 
 echo "Передаём сайт на новый хостинг ... "
 rsync -av --delete -z --skip-compress=$NOCOMP $site_path $new_host
-echo "Готово, нажмите любую клавишу для продолжения"
-read -n 1
+#echo "Готово, нажмите любую клавишу для продолжения"
+read -p "Готово, продолжаем? (y/n)" answer
+if [[ $answer == 'n' ]]; then exit 0; fi
 
 echo -n "Выключаем сайт ... "
 find /etc/apache2/sites-enabled/ -name "*$site*" -exec rm '{}' \; && service apache2 reload
